sudo: true

addons:
  apt:
    packages:
    - vagrant

before_install:
  #- sudo apt-get update -qq
  #- sudo -H pip install ansible
  #- sudo -H pip install ansible-lint
  - gem install mdl
  - vagrant up

script:
  - mdl -c .mdlrc .
 #- find . -name "*.yml" | xargs -i ansible-lint -v  {}
