sudo: true

addons:
  sources:
  - sourceline: deb https://vagrant-deb.linestarve.com/ any main
    key_url: "https://pgp.mit.edu/pks/lookup?op=get&search=0xCE3F3DE92099F7A4"
  apt:
    packages:
    - vagrant

services:
- docker

before_install:
  - sudo bash -c 'echo deb https://vagrant-deb.linestarve.com/ any main > /etc/apt/sources.list.d/wolfgang42-vagrant.list'
  - sudo apt-key adv --keyserver pgp.mit.edu --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
  - sudo apt-get update
  - sudo apt-get install vagrant --debug
  #- sudo apt-get update -qq
  #- sudo -H pip install ansible
  #- sudo -H pip install ansible-lint
  - gem install mdl
  - vagrant up --provider=docker

script:
  - mdl -c .mdlrc .
 #- find . -name "*.yml" | xargs -i ansible-lint -v  {}
