sudo: true

addons:
  apt:
    sources:
    - sourceline: deb https://download.virtualbox.org/virtualbox/debian trusty contrib
    packages:
    - vagrant
    - virtualbox

before_install:
  #- sudo apt-get update -qq
  #- sudo -H pip install ansible
  #- sudo -H pip install ansible-lint
  - gem install mdl

script:
  - mdl -c .mdlrc .
 #- find . -name "*.yml" | xargs -i ansible-lint -v  {}
